name = "brenda-km-really_simple"
data_dir = "data/prepared/brenda_km"
stan_file = "src/stan/really_simple.stan"
do_not_run = false

[sample_kwargs]
show_progress = true
save_warmup = false
iter_warmup = 400
iter_sampling = 400
max_treedepth = 11
chains = 4
refresh = 1

[sample_kwargs_cross_validation]
chains = 1