name = "final"
stan_file = "src/stan/final.stan"
data_file = "data/stan_input/lit_lik_nat.json"
coords_file = "data/coords/lit_lik_nat.json"
dims_file = "data/dims/lit_lik_nat.json"

[sample_kwargs]
show_progress = true
save_warmup = true
iter_warmup = 500
iter_sampling = 500
max_treedepth = 13
chains = 4
refresh = 1
