name = "new_model"
stan_file = "src/stan/new_model.stan"
data_file = "data/prepared/data_prepared_natural_substrates_only.csv"
priors_file = "data/priors/priors.csv"
likelihood = true

[sample_kwargs]
show_progress = true
save_warmup = true
iter_warmup = 1000
iter_sampling = 1000
max_treedepth = 11
chains = 2
refresh = 1
