name = "sabio-really-simple"
stan_file = "src/stan/really_simple.stan"
data_dir = "data/prepared/sabio"
run_cross_validation = true

[sample_kwargs]
show_progress = true
save_warmup = false
iter_warmup = 800
iter_sampling = 800
max_treedepth = 11
chains = 4
refresh = 1

[sample_kwargs_cross_validation]
chains = 1
