name = "simple-kcat"
stan_file = "src/stan/simple.stan"
data_dir = "data/prepared/kcat_tenfold"
# do_not_run = true
run_cross_validation = true

[sample_kwargs]
show_progress = true
save_warmup = false
iter_warmup = 400
iter_sampling = 400
max_treedepth = 11
chains = 4
refresh = 1

[sample_kwargs_cross_validation]
chains = 1
