ORGANISM = "Trypanosoma brucei"
REACTION_TO_EC4 = {
    "HXK": "2.7.1.1",
    "PGK": "2.7.2.3",
    "PGI": "5.3.1.9",
    # "TR": ,
    "G3PDH": "1.2.12",
    # "PyrT": "",
    "PYK": "2.7.1.40",
    "GPO": "1.1.3.21",
    "G6PDH": "1.1.1.363",
    # "_6PGDH": ,
    "GAPDH": "1.2.1.12",  # could be "1.2.1.59"?
    "TPI": "5.3.1.1",
    # "GlcT": ,
    "PGAM": "5.4.2.1",  # could be "5.4.2.11", "5.4.2.12"
    "ENO": "4.2.1.11",
    "PGK": "2.7.2.3",
    # "PPI": ,
    "PGL": "3.1.1.31",
    "PFK": "2.7.1.11",
    "G6PP": "3.1.3.58",  # could be "3.1.3.9",
    # "ALD": ,
}
P_NAMES = [
    "CO2_c",
    "Rib5P_c",
    "Pi_g",
    "Rib5P_g",
    "CO2_g",
    "O2_c",
    "Glc_e",
    "Pyr_e",
    "Gly_e",
    "cytosol",
    "glycosome",
    "default",
    "TPI_g_Vmax",
    "TPI_g_Keq",
    "TPI_g_KmDHAP",
    "TPI_g_KmGA3P",
    "PYK_c_Vmax",
    "PYK_c_KmPEP",
    "PYK_c_KiATP",
    "PYK_c_KiADP",
    "PYK_c_n",
    "PYK_c_KmADP",
    "PYK_c_Keq",
    "PYK_c_KmPyr",
    "PYK_c_KmATP",
    "PFK_g_Vmax",
    "PFK_g_Ki1",
    "PFK_g_KmFru6P",
    "PFK_g_KmATP",
    "PFK_g_Keq",
    "PFK_g_KsATP",
    "PFK_g_KmADP",
    "PFK_g_Ki2",
    "G6PDH_g_Vmax",
    "G6PDH_g_Keq",
    "G6PDH_g_KmGlc6P",
    "G6PDH_g_KmNADP",
    "G6PDH_g_Km6PGL",
    "G6PDH_g_KmNADPH",
    "PGAM_c_Vmax",
    "PGAM_c_Keq",
    "PGAM_c_Km3PGA",
    "PGAM_c_Km2PGA",
    "PyrT_c_Vmax",
    "PyrT_c_KmPyr",
    "G6PDH_c_Vmax",
    "G6PDH_c_Keq",
    "G6PDH_c_KmGlc6P",
    "G6PDH_c_KmNADP",
    "G6PDH_c_Km6PGL",
    "G6PDH_c_KmNADPH",
    "ENO_c_Vmax",
    "ENO_c_Keq",
    "ENO_c_Km2PGA",
    "ENO_c_KmPEP",
    "HXK_g_Vmax",
    "HXK_g_Keq",
    "HXK_g_KmGlc",
    "HXK_g_KmATP",
    "HXK_g_KmGlc6P",
    "HXK_g_KmADP",
    "_3PGAT_g_k",
    "NADPHu_c_k",
    "HXK_c_Vmax",
    "HXK_c_Keq",
    "HXK_c_KmGlc",
    "HXK_c_KmATP",
    "HXK_c_KmGlc6P",
    "HXK_c_KmADP",
    "NADPHu_g_k",
    "AK_c_k1",
    "AK_c_k2",
    "G6PP_c_Vmax",
    "G6PP_c_Keq",
    "G6PP_c_KmGlc6P",
    "G6PP_c_KmGlc",
    "_6PGDH_g_Vmax",
    "_6PGDH_g_Keq",
    "_6PGDH_g_Km6PG",
    "_6PGDH_g_KmNADP",
    "_6PGDH_g_KmRul5P",
    "_6PGDH_g_KmNADPH",
    "PGI_g_Vmax",
    "PGI_g_KmGlc6P",
    "PGI_g_Keq",
    "PGI_g_KmFru6P",
    "PGI_g_Ki6PG",
    "AK_g_k1",
    "AK_g_k2",
    "TOX_c_k",
    "GDA_g_k",
    "PGL_c_Vmax",
    "PGL_c_Keq",
    "PGL_c_Km6PGL",
    "PGL_c_Km6PG",
    "PGL_c_k",
    "_6PGDH_c_Vmax",
    "_6PGDH_c_Keq",
    "_6PGDH_c_Km6PG",
    "_6PGDH_c_KmNADP",
    "_6PGDH_c_KmRul5P",
    "_6PGDH_c_KmNADPH",
    "PPI_c_Vmax",
    "PPI_c_Keq",
    "PPI_c_KmRul5P",
    "PPI_c_KmRib5P",
    "PPI_g_Vmax",
    "PPI_g_Keq",
    "PPI_g_KmRul5P",
    "PPI_g_KmRib5P",
    "k1",
    "k2",
    "GlcT_c_Vmax",
    "GlcT_c_KmGlc",
    "GlcT_c_alpha",
    "PGL_g_Vmax",
    "PGL_g_Keq",
    "PGL_g_Km6PGL",
    "PGL_g_Km6PG",
    "PGL_g_k",
    "TR_c_Vmax",
    "TR_c_Keq",
    "TR_c_KmTS2",
    "TR_c_KmNADPH",
    "TR_c_KmTSH2",
    "TR_c_KmNADP",
    "PGK_g_Vmax",
    "PGK_g_Keq",
    "PGK_g_Km13BPGA",
    "PGK_g_KmADP",
    "PGK_g_Km3PGA",
    "PGK_g_KmATP",
    "G3PDH_g_Vmax",
    "G3PDH_g_Keq",
    "G3PDH_g_KmDHAP",
    "G3PDH_g_KmNADH",
    "G3PDH_g_KmGly3P",
    "G3PDH_g_KmNAD",
    "ATPu_c_k",
    "GK_g_Vmax",
    "GK_g_Keq",
    "GK_g_KmGly3P",
    "GK_g_KmADP",
    "GK_g_KmGly",
    "GK_g_KmATP",
    "ALD_g_Vmax",
    "ALD_g_KmFru16BP",
    "ALD_g_KiATP",
    "ALD_g_KiADP",
    "ALD_g_KiAMP",
    "ALD_g_Keq",
    "ALD_g_KmGA3P",
    "ALD_g_KmDHAP",
    "ALD_g_KiGA3P",
    "GAPDH_g_Vmax",
    "GAPDH_g_Keq",
    "GAPDH_g_KmGA3P",
    "GAPDH_g_KmNAD",
    "GAPDH_g_Km13BPGA",
    "GAPDH_g_KmNADH",
    "GPO_c_Vmax",
    "GPO_c_KmGly3P",
]
